### ISSUE TITLE
Running as a server no longer works

### ISSUE THREAD

**Issue by j-maynard** [hugomods/docker#63] opened 2023-12-19 09:53 UTC
Running the Docker image in server mode no longer works.  The [Docs say to run in server](https://hugomods.com/docs/docker/#start-hugo-server) mode like so:

```
docker run -p 8080:8080 \
  -v ${PWD}:/src \
  hugomods/hugo \
  hugo server --bind 0.0.0.0 -p 8080
```

However this just results in hugo building the site and not running the server.  Tested using docker desktop on a Mac.  A screenshot also helps.

<img width="1043" alt="image" src="https://github.com/hugomods/docker/assets/29251905/c9291787-bced-4d77-aae7-08b5935409ac">

**Comment by razonyang** [comment] 2023-12-19 10:12
> However this just results in hugo building the site and not running the server. 

Could you please provide the full log? Both of `hugo` and `hugo server` will produce the following similar information, but I didn't found it from your screenshot.

![image](https://github.com/hugomods/docker/assets/17720932/031aa707-a9fc-4912-b1db-0ef8fa04b935)

**Comment by razonyang** [comment] 2023-12-19 10:20
I couldn't reproduce it by using the same Docker image, let me know if there is any additional information I missed.

![image](https://github.com/hugomods/docker/assets/17720932/84dc6ec6-f5c0-4dff-8635-12ca82ecafaf)

**Comment by razonyang** [comment] 2023-12-24 08:39
I'm closing this as per no futher information, please comment below if there any additional information.

**Closed by razonyang** 2023-12-24 08:39 UTC
Labels: good first issue

**Comment by j-maynard** [comment] 2024-01-09 12:34
I can confirm this is an issue with the ARM64 builds of the image.  Running in server results in hugo apparently building the site and not passing the server argument to the binary inside the image.

<img width="2045" alt="image" src="https://github.com/hugomods/docker/assets/29251905/b51ccd62-81b9-45e3-b96d-e159ad66fa63">

**Comment by j-maynard** [comment] 2024-01-09 12:37
Sorry I've been on Holiday for the Christmas period and I've just got back.  here's the output of both commands:

<img width="2001" alt="image" src="https://github.com/hugomods/docker/assets/29251905/853636be-f011-439f-b718-8f4e9a488902">

**Comment by razonyang** [comment] 2024-01-09 13:26
Hi @j-maynard, according to the screenshot you provided above, the `... hugo server ...` does't finish yet, it should produce similar info as the second command, or display some errors, I guess the process comsumed too many memory and was terminated by OS.

I can reproduce it with limited ram for container.

![image](https://github.com/hugomods/docker/assets/17720932/13ea4c23-b998-4590-a1af-44d645e922de)

Gif:

![peek2](https://github.com/hugomods/docker/assets/17720932/717d6acf-191e-46bf-8aee-d4bfcf3ebb0b)

You can check the system/memory log or sth similar, `/var/log/kern.log` for Linux (Ubuntu), I don't know how on macOS, please google yourself.

Back to the issue, if it's an _out of memory_ issue, I don't have a solution for this.

**Comment by j-maynard** [comment] 2024-01-10 00:40
You were right it was a memory issue in part because of the way server runs and the sheer size of the GitLab Handbook.  Hugo unhelpfully doesn't tell us when it runs out of memory or exits with a non-zero exit code.  Changing things so that it use `--renderToDisk` massively reduces the memory footprint though at the expense of performance.

Thank you for your help with this... I can share this with my team.
